### PR TITLE
CP-2059 Support auto-retying requests that fail with a null response

### LINKED ISSUE #173: Allow HTTP requests with status 0 to be retried
When an XHR request is made from the browser, there are some special case failures that may occur. The browser may not be able to complete the request because there is no network connection, or it may refuse to complete the request as a security measure (example: server did not return access-control headers, thus rejecting the cross-origin request). In the network tab, you'll likely see that the request returned with a status code of 0. This is not an official HTTP status code, but rather a special code used by browsers to indicate the type of failure to the developer.

In code, a response will most likely not be received at all. Instead, an error event will be triggered on the XHR instance. With our current implementation, this results in the error being raised (and then wrapped in a `RequestException`) and a null `response`. Additionally, our "can retry" logic treats a null `response` as a non-retryable failure. I'm not sure this should be the case.

On one hand, we don't know exactly why a request failed when it fails like this, so it may be useless to retry it (CORS). On the other hand, one of the more common scenarios in which this would happen is a lack of network connection (offline mode or intermittent connectivity), which would benefit from retrying.

**tl;dr:** we should consider allowing retries for failed requests where the failure is unknown.

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Issue
Fix #173 

## Solution
This will allow auto-retrying of requests that have null responses. Consumers will need to add a `test` method to `request.autoRetry` that checks for a `null` response and returns `true` to enable the functionality.

@evanweible-wf thoughts?

## Testing
Added an integration test that causes a `null` response and ensures it gets retried.

@trentgrover-wf
@evanweible-wf
@dustinlessard-wf
@jayudey-wf
@sebastianmalysa-wf 
@srinivasdhanwada-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@maxwellpeterson-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/77526396/addTicketToTitle'>here</a> to have Rosie create one for you.

File: lib/src/http/common/request.dart [hunk 1]
```diff
@@ -495,10 +495,8 @@ abstract class CommonRequest extends Object
     if (requestException.error is TimeoutException && autoRetry.forTimeouts)
       return true;
 
-    if (response == null) return false;
-
     bool willRetry = autoRetry.forHttpMethods.contains(method) &&
-        autoRetry.forStatusCodes.contains(response.status);
+        autoRetry.forStatusCodes.contains(response?.status ?? 0);
```
Comment (evanweible-wf) [inline lib/src/http/common/request.dart]: Could you do this without null-aware operators for now?

Comment (maxwellpeterson-wf) [inline lib/src/http/common/request.dart]: Fixed

File: lib/src/http/common/request.dart [hunk 2]
```diff
@@ -495,10 +495,14 @@ abstract class CommonRequest extends Object
     if (requestException.error is TimeoutException && autoRetry.forTimeouts)
       return true;
 
-    if (response == null) return false;
+    // TODO replace with null-aware operators once this library uses them.
+    var status = response != null ? response.status : 0;
+    if (status == null) {
```
Comment (trentgrover-wf) [inline lib/src/http/common/request.dart]: status can never be null here, right?

Comment (trentgrover-wf) [inline lib/src/http/common/request.dart]: nm, i see...

**Comment by trentgrover-wf** [comment]
I'm not sure all of this is necessary.  In dart it's permissible for a List<int> to contain null as an entry, so consumers can specify `null` in `forStatusCodes` and it will work (and it would be more self documenting)

maybe you only need:
```
var status = response != null ? response.status : null;
```

**Comment by maxwellpeterson-wf** [comment]
`0` is a real status code used by browsers though for a failed request, so this is more in line with that.

@evanweible-wf thoughts?

**Comment by evanweible-wf** [comment]
I changed my mind on the 0 status code - since it's not actually in the HTTP spec, we shouldn't introduce any knowledge of it even if browsers do use it. I don't like having consumers put `null` in their `forStatusCodes` list, either. But they can still detect it by supplying a `test` method that checks for a `null` response, so I think we should go that route.

**Comment by maxwellpeterson-wf** [comment]
Done

**Comment by trentgrover-wf** [comment]
+1

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - passing CI with test exercising functionality
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.
